---
codecov:
  require_ci_to_pass: true

coverage:
  ignore:
    - "tests/**"
  status:
    patch:
      default:
        target: auto
    project:
      default:
        threshold: 0.3%

flags:
  unit-tests:
    carryforward: true
    paths:
      - plugins/

comment:
  layout: "reach,diff,flags,files"
  behavior: default

fixes:
  - "source/::"
